### PR TITLE
Png2asset refractor

### PR DESCRIPTION
**Pull request by LaroldsJubilantJunkyard**
i've moved entry point into main.cpp.
many things into separate structs or classes.
And each to their own file.
process_arguments.cpp contains all the data passed from the command line.
I believe i've matched all the recent changes with the nes addition, adding -o, and such.

### CODE REVIEW

**Comment by bbbbbr** [comment]
A couple things for this PR to keep it moving along:

From discord (not sure if this got added?):
> Larold: i think i've got all commits. i'm only unsure if this one is neccessary https://github.com/gbdk-2020/gbdk-2020/commit/0d0b40415db18c231ff8ad7177c2aed522cd3022
>
> bbbbbr: Yes, we will want that since it fixes some behavior with use_source_tileset
> https://github.com/gbdk-2020/gbdk-2020/pull/564#issuecomment-1667806843


There's a build error that can be fixed with this change to the makefile:
~~~
- SRCS := lodepng.cpp png2asset.cpp rgb_to_nes_lut.cpp image_utils.cpp
+ SRCS := cmp_int_color.cpp  image_data.cpp lodepng.cpp  map_attributes.cpp  metasprites.cpp png2asset.cpp rgb_to_nes_lut.cpp export.cpp image_utils.cpp main.cpp maps.cpp palettes.cpp process_arguments.cpp tiles.cpp
~~~


There should be testing of all example projects in GBDK (make sure they build and output looks right) as and ideally some of our own projects to ensure that there haven't been any regressions. Considering the number of platforms and options, there are a lot of potential combinations where issues could manifest.

Currently getting errors when building:
* cross-platform/large_map
* cross-platform/logo
* cross-platform/metasprites
* gb/apa_image
* gb/hblank_copy
* gb/sgb_border

Some graphical errors on this project, but I'm not sure if that's due to missing upstream fixes that came in later (I built with the version of gbdk that your repo fork has):
* cross-platform/gbdecompress (sms/gg)

**Comment by bbbbbr** [comment]
Seeing a handful of warnings when building on Linux with the latest commits in this branch, mainly signed vs unsigned clashing. Ideally all gbdk support tools build with no warnings.
```
g++ -Os -Wall -g   -c -o map_attributes.o map_attributes.cpp
map_attributes.cpp: In function ‘unsigned char GetMapAttribute(size_t, size_t, PNG2AssetData*)’:
map_attributes.cpp:23:14: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   23 |         if(x < assetData->args->map_attributes_size.width && y < assetData->args->map_attributes_size.height)
      |            ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
map_attributes.cpp:23:64: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   23 |         if(x < assetData->args->map_attributes_size.width && y < assetData->args->map_attributes_size.height)
      |                                                              ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
map_attributes.cpp: In function ‘void AlignMapAttributes(PNG2AssetData*)’:
map_attributes.cpp:69:45: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   69 |                         for(size_t x = 0; x < assetData->args->map_attributes_size.width; x++)
      |                                           ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
map_attributes.cpp: In function ‘void PackMapAttributes(PNG2AssetData*)’:
map_attributes.cpp:92:29: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   92 |         for(size_t y = 0; y < assetData->args->map_attributes_packed_size.height; y++)
      |                           ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
map_attributes.cpp:94:37: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   94 |                 for(size_t x = 0; x < assetData->args->map_attributes_packed_size.width; x++)
      |                                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
g++ -Os -Wall -g   -c -o metasprites.o metasprites.cpp
g++ -Os -Wall -g   -c -o png2asset.o png2asset.cpp
g++ -Os -Wall -g   -c -o rgb_to_nes_lut.o rgb_to_nes_lut.cpp
g++ -Os -Wall -g   -c -o export.o export.cpp
export.cpp: In function ‘bool export_c_file(PNG2AssetData*)’:
export.cpp:364:61: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  364 |                                         for(size_t i = 0; i < assetData->args->map_attributes_packed_size.width; ++i)
      |                                                           ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export.cpp:367:69: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  367 |                                                 for(size_t j = 0; j < assetData->args->map_attributes_packed_size.height; ++j)
      |                                                                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export.cpp:375:61: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  375 |                                         for(size_t j = 0; j < assetData->args->map_attributes_packed_size.height; ++j)
      |                                                           ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export.cpp:378:69: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  378 |                                                 for(size_t i = 0; i < assetData->args->map_attributes_packed_size.width; ++i)
      |                                                                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
g++ -Os -Wall -g   -c -o image_utils.o image_utils.cpp
g++ -Os -Wall -g   -c -o main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:50:21: warning: statement has no effect [-Wunused-value]
   50 |                 for(sourceTilesetsIterator; sourceTilesetsIterator < arguments.source_tilesets.end(); sourceTilesetsIterator++) {
      |                     ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bbbbbr** [comment]
For the following option vars, if I give them a default of `true` in `process_arguments.cpp` on the system where conversion fails for some example projects (such as large map), then the build starts working for that example project.

```
args->includeTileData = true;
args->includedMapOrMetaspriteData = true;
args->include_palettes = true;
```
Without those changes it's missing the associated data controlled by each of the options (such as missing palette data).

Maybe there is something different in the execution environment for the systems where it fails with regard to how those variables get initialized? (such that they get initialized to false, which seems strange)

**Comment by bbbbbr** [comment]
On the system that doesn't have the missing png2asset output content problem mentioned above, the Large Map does build but it has a different issue - lots of  bank overflows that don't seem to be in the 4.2 release or mainline develop. 

Maybe it's getting some kind of excessive data in the output. Are you able to replicate that at all?


```
./../..//bin/png2asset res/bigmap.png -map -bpp 2 -max_palettes 4 -pack_mode gb -noflip -c obj/gb/res/bigmap.c
../../../bin/lcc -Wf-MMD -Iobj/gb  -msm83:gb -c -o obj/gb/bigmap.o obj/gb/res/bigmap.c
../../../bin/lcc -Wf-MMD -Iobj/gb  -msm83:gb -c -o obj/gb/large_map.o src/large_map.c
src/large_map.c:179: warning 158: overflow in implicit constant conversion
../../../include/gb/gb.h:2065: warning 126: unreachable code
../../../bin/lcc -Wl-yt0x1B -autobank   -Wl-j -Wm-yoA -Wm-ya4 -Wb-ext=.rel -Wb-v  -Wf-MMD -Iobj/gb  -msm83:gb -o build/gb/large-map.gb obj/gb/bigmap.o obj/gb/large_map.o 

=== Banks assigned: 255 -> 0 (allowed range 1 -> 255). Max including fixed: 0) ===

Warning: Multiple write of    13 bytes at 0xf3c1 -> 0xf3cd writes:(0xf3c1 -> 0xf3cd, 0xc000 -> 0xffff)
Warning: Multiple write of    62 bytes at 0xf260 -> 0xf29d writes:(0xf260 -> 0xf29d, 0xc000 -> 0xffff)
Warning: Multiple write of     1 bytes at 0x20 -> 0x20 writes:(0x20 -> 0x20, 0x20 -> 0x3fff)
Warning: Multiple write of     5 bytes at 0x28 -> 0x2c writes:(0x28 -> 0x2c, 0x20 -> 0x3fff)
Warning: Multiple write of     7 bytes at 0x30 -> 0x36 writes:(0x30 -> 0x36, 0x20 -> 0x3fff)
Warning: Multiple write of     8 bytes at 0x40 -> 0x47 writes:(0x40 -> 0x47, 0x20 -> 0x3fff)
Warning: Multiple write of    96 bytes at 0x80 -> 0xdf writes:(0x80 -> 0xdf, 0x20 -> 0x3fff)
Warning: Multiple write of     1 bytes at 0xf0 -> 0xf0 writes:(0xf0 -> 0xf0, 0x20 -> 0x3fff)
Warning: Multiple write of     2 bytes at 0x100 -> 0x101 writes:(0x100 -> 0x101, 0x20 -> 0x3fff)
Warning: Multiple write of    54 bytes at 0x104 -> 0x139 writes:(0x104 -> 0x139, 0x20 -> 0x3fff)
Warning: Multiple write of   183 bytes at 0x144 -> 0x1fa writes:(0x144 -> 0x1fa, 0x20 -> 0x3fff)
Warning: Multiple write of 15872 bytes at 0x200 -> 0x3fff writes:(0x200 -> 0x3fff, 0x20 -> 0x3fff)
Warning: Multiple write of 16384 bytes at 0x4000 -> 0x7fff writes:(0x4000 -> 0x7fff, 0x4000 -> 0x7fff)
Warning: Multiple write of 16384 bytes at 0x8000 -> 0xbfff writes:(0x8000 -> 0xbfff, 0x8000 -> 0xbfff)
Warning: Multiple write of    13 bytes at 0xf3c1 -> 0xf3cd writes:(0xf3c1 -> 0xf3cd, 0xc000 -> 0xffff)
Warning: Multiple write of    62 bytes at 0xf260 -> 0xf29d writes:(0xf260 -> 0xf29d, 0xc000 -> 0xffff)
Warning: Multiple write of 16384 bytes at 0xc000 -> 0xffff writes:(0xc000 -> 0xffff, 0xc000 -> 0xffff)
Warning: Multiple write of 16384 bytes at 0x4000 -> 0x7fff writes:(0x4000 -> 0x7fff, 0x4000 -> 0x7fff)
Warning: Multiple write of 16384 bytes at 0x4000 -> 0x7fff writes:(0x4000 -> 0x7fff, 0x4000 -> 0x7fff)
Warning: Multiple write of 16384 bytes at 0x8000 -> 0xbfff writes:(0x8000 -> 0xbfff, 0x8000 -> 0xbfff)
Warning: Multiple write of 16384 bytes at 0x8000 -> 0xbfff writes:(0x8000 -> 0xbfff, 0x8000 -> 0xbfff)
Warning: Multiple write of 12896 bytes at 0xc000 -> 0xf25f writes:(0xc000 -> 0xffff, 0xc000 -> 0xf25f)
Warning: Multiple write of 12896 bytes at 0xc000 -> 0xf25f writes:(0xc000 -> 0xffff, 0xc000 -> 0xf25f)
Warning: Multiple write of     1 bytes at 0xf3c0 -> 0xf3c0 writes:(0xc000 -> 0xffff, 0xf3c0 -> 0xf3c0)
Warning: Multiple write of     1 bytes at 0xf3c0 -> 0xf3c0 writes:(0xc000 -> 0xffff, 0xf3c0 -> 0xf3c0)
Warning: Multiple write of   290 bytes at 0xf29e -> 0xf3bf writes:(0xc000 -> 0xffff, 0xf29e -> 0xf3bf)
Warning: Multiple write of   290 bytes at 0xf29e -> 0xf3bf writes:(0xc000 -> 0xffff, 0xf29e -> 0xf3bf)
Warning: Possible overflow from Bank 0 into Bank 3
make[3]: Leaving directory '/gbdk/examples/cross-platform/large_map'
make build-target PORT=sm83 PLAT=gb EXT=gbc
make[3]: Entering directory '/gbdk/examples/cross-platform/large_map'

../../..//bin/png2asset res/bigmap.png -map -use_map_attributes -bpp 2 -max_palettes 8 -pack_mode gb -c obj/gbc/res/bigmap.c
../../../bin/lcc -Wf-MMD -Iobj/gbc  -msm83:gb -c -o obj/gbc/bigmap.o obj/gbc/res/bigmap.c
../../../bin/lcc -Wf-MMD -Iobj/gbc  -msm83:gb -c -o obj/gbc/large_map.o src/large_map.c
src/large_map.c:179: warning 158: overflow in implicit constant conversion
../../../include/gb/gb.h:2065: warning 126: unreachable code
../../../bin/lcc -Wl-yt0x1B -Wm-yc -autobank   -Wl-j -Wm-yoA -Wm-ya4 -Wb-ext=.rel -Wb-v  -Wf-MMD -Iobj/gbc  -msm83:gb -o build/gbc/large-map.gbc obj/gbc/bigmap.o obj/gbc/large_map.o 

=== Banks assigned: 255 -> 0 (allowed range 1 -> 255). Max including fixed: 0) ===

Warning: Multiple write of     1 bytes at 0x20 -> 0x20 writes:(0x20 -> 0x20, 0x20 -> 0x3fff)
Warning: Multiple write of     5 bytes at 0x28 -> 0x2c writes:(0x28 -> 0x2c, 0x20 -> 0x3fff)
Warning: Multiple write of     7 bytes at 0x30 -> 0x36 writes:(0x30 -> 0x36, 0x20 -> 0x3fff)
Warning: Multiple write of     8 bytes at 0x40 -> 0x47 writes:(0x40 -> 0x47, 0x20 -> 0x3fff)
Warning: Multiple write of    96 bytes at 0x80 -> 0xdf writes:(0x80 -> 0xdf, 0x20 -> 0x3fff)
Warning: Multiple write of     1 bytes at 0xf0 -> 0xf0 writes:(0xf0 -> 0xf0, 0x20 -> 0x3fff)
Warning: Multiple write of     2 bytes at 0x100 -> 0x101 writes:(0x100 -> 0x101, 0x20 -> 0x3fff)
Warning: Multiple write of    54 bytes at 0x104 -> 0x139 writes:(0x104 -> 0x139, 0x20 -> 0x3fff)
Warning: Multiple write of   183 bytes at 0x144 -> 0x1fa writes:(0x144 -> 0x1fa, 0x20 -> 0x3fff)
Warning: Multiple write of 15872 bytes at 0x200 -> 0x3fff writes:(0x200 -> 0x3fff, 0x20 -> 0x3fff)
Warning: Multiple write of 16384 bytes at 0x4000 -> 0x7fff writes:(0x4000 -> 0x7fff, 0x4000 -> 0x7fff)
Warning: Multiple write of 16384 bytes at 0x8000 -> 0xbfff writes:(0x8000 -> 0xbfff, 0x8000 -> 0xbfff)
Warning: Multiple write of 16384 bytes at 0xc000 -> 0xffff writes:(0xc000 -> 0xffff, 0xc000 -> 0xffff)
Warning: Multiple write of 16384 bytes at 0x4000 -> 0x7fff writes:(0x4000 -> 0x7fff, 0x4000 -> 0x7fff)
Warning: Multiple write of 16384 bytes at 0x4000 -> 0x7fff writes:(0x4000 -> 0x7fff, 0x4000 -> 0x7fff)
Warning: Multiple write of 16384 bytes at 0x8000 -> 0xbfff writes:(0x8000 -> 0xbfff, 0x8000 -> 0xbfff)
Warning: Multiple write of 16384 bytes at 0x8000 -> 0xbfff writes:(0x8000 -> 0xbfff, 0x8000 -> 0xbfff)
Warning: Multiple write of 16384 bytes at 0xc000 -> 0xffff writes:(0xc000 -> 0xffff, 0xc000 -> 0xffff)
Warning: Multiple write of 16384 bytes at 0xc000 -> 0xffff writes:(0xc000 -> 0xffff, 0xc000 -> 0xffff)
Warning: Multiple write of    32 bytes at 0x10000 -> 0x1001f writes:(0x10000 -> 0x1001f, 0x10000 -> 0x11a9e)
Warning: Possible overflow from Bank 0 into Bank 3
Warning: Possible overflow from Bank 0 into Bank 4
make[3]: Leaving directory '/gbdk/examples/cross-platform/large_map'
make build-target PORT=z80 PLAT=gg EXT=gg
make[3]: Entering directory '/gbdk/examples/cross-platform/large_map'
```

**Comment by LaroldsJubilantJunkyard** [comment]
> Warning: Multiple write of

I was able to successfully build for each platform with no overflow issues once i added the default values you mentioned, plus pack mode (and maybe one more, i forget). Now i just need to look into those warnings.

**Comment by bbbbbr** [comment]
I pulled the updates and did a `make distclean` (clears the build output folder) + `make`, then did a rebuild of examples on the two computers.

I'm able to build on both computers without errors and bank overflow warnings now.

After building the examples I did a diff (using Meld - https://meldmerge.org/) between the example build folders of this fork and of same for gbdk mainline. 
- In `cross-platform/large_map` the converted map attribute data for NES and GBC is different in this fork (in a way that looks incorrect in the built roms). Same is true `cross-platform/logo`, but since they use incbin the diff shows up for the .asm files instead of .c (The attributes difference happens on one computer, on another there was some slightly different output.) 
- For `cross-platform/metasprites`:
  - The Pivot constants are lowercase now when they should be uppercase. For example: `#define sprite_PIVOT_X 32` (existing) vs `#define sprite_pivot_x 32` (new)
  - The attribute data for NES and GBC also looks different in a way that produces incorrect output.
- For `gb/sgb_border` the generated map data looks different (likely incorrect, though I don't have bgb installed on the computer I'm testing with at the moment so I'm not able to see how the border is different visually). (Happens on one computer, not the other)

It's getting closer :+1:

**Comment by bbbbbr** [comment]
Did a sync and rebuild and two issues:

1. The metasprite constant case and names still don't quite match:
~~~
#define sprite_PIVOT_x (should be sprite_PIVOT_X)
#define sprite_PIVOT_y (should be sprite_PIVOT_Y)
#define sprite_PIVOT_width  (should be sprite_PIVOT_W)
#define sprite_PIVOT_height (should be sprite_PIVOT_H)
~~~

2. Looks like the `rgb_to_nes[]` const LUT/lookup table isn't wired up. It gets compiled as a standalone cpp file, and there's a reference for it in the PNG2AssetData class which isn't connected to the data in that standalone source file. 
So for the `cross-platform/logo` example where the NES build uses `-use_nes_colors` with png2asset it's outputting all zeros for the palette. No pref on how the LUT is connected. Could be part of the main class or just standalone since the LUT doesn't depend or interact with anything else in png2asset.

With those two altered the example output builds look identical for relevant files to the existing png2asset on both of my computers.

**Comment by bbbbbr** [comment]
Built some of my own projects and came across this:

* `keep_palette_order` needs to have the palette buffer copied when loading the png, otherwise the buffer it points to gets freed and then holds invalid data when returns.
```diff
gbdk-support/png2asset/image_data.cpp:58: int ReadImageData_KeepPaletteOrder(  PNG2AssetData* assetData, string  input_fil │

    assetData->image.total_color_count = palette_count * assetData->image.colors_per_pal;
---    assetData->image.palette = state.info_png.color.palette;
+++    // Copy the palette data since the source buffer (state...) won't exist outside the scope of this function
+++    assetData->image.palette = new unsigned char[assetData->image.total_color_count * RGBA32_SZ];
+++    memcpy(assetData->image.palette, state.info_png.color.palette, assetData->image.total_color_count * RGBA32_SZ);
```

**Comment by LaroldsJubilantJunkyard** [comment]
> Built some of my own projects and came across this:
> 
> * `keep_palette_order` needs to have the palette buffer copied when loading the png, otherwise the buffer it points to gets freed and then holds invalid data when returns.
> 
> ```diff
> gbdk-support/png2asset/image_data.cpp:58: int ReadImageData_KeepPaletteOrder(  PNG2AssetData* assetData, string  input_fil │
> 
>     assetData->image.total_color_count = palette_count * assetData->image.colors_per_pal;
> ---    assetData->image.palette = state.info_png.color.palette;
> +++    // Copy the palette data since the source buffer (state...) won't exist outside the scope of this function
> +++    assetData->image.palette = new unsigned char[assetData->image.total_color_count * RGBA32_SZ];
> +++    memcpy(assetData->image.palette, state.info_png.color.palette, assetData->image.total_color_count * RGBA32_SZ);
> ```

for the record, this and previous suggestions have been done.

**Comment by bbbbbr** [comment]
Merging, thanks for all the work on this. If further issues with the output show up we'll fix as we go along.

**Pull request merged**
