### PR TITLE
png2mtspr: exporting metasprite and tile count 

### PR DESCRIPTION
**Pull request by uberyoji**
Export amount of tiles and metasprites to header file

### CODE REVIEW

**Comment by uberyoji** [comment]
It is my first PR so bear with me.

**Comment by untoxa** [comment]
if you define *_METASPRITE_COUNT and *%_TILE_COUNT, it makes sense to use those in the generated source below

**Comment by bbbbbr** [comment]
Might also want to check how this overlaps with the work @Zal0 is currently doing on the feature/png2mtspr branch.
https://github.com/gbdk-2020/gbdk-2020/tree/feature/png2mtspr

**Comment by Zal0** [comment]
Yeah, I was gonna say that. Already working on this

**Comment by uberyoji** [comment]
> Yeah, I was gonna say that. Already working on this

Whoa ok, the upcoming changes are quite nice. If you are submitting this soon, I will close my PR.

**Comment by untoxa** [comment]
there is always another option:
```
tile_count = sizeof(tile_data)/16;
metasprites_count = sizeof(metasprite)/sizeof(metasprite[0]);
```
those values will be calculated at compile time and equivalent for those defines.

**Pull request closed without merging**
